version: "3"
services:

  client:
    image: dev-client
    ports:
      - 3000:3000
    depends_on:
      - server

  server:
    image: chat_server
    ports:
      - 5002:5002
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    links:
      - redis

  redis:
    image: redis:5.0.7
    ports:
      - 6379:6379
      - 6370:6370
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
  minio-data:
