apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: davealonbehr/endless-chat-client:latest
          ports:
            - containerPort: 3000
          
          
          # env:
          #   - name: REACT_APP_CHAT_SERVER_HOST
          #     value: SERVER_CLUSTER_IP_SERVICE_SERVICE_HOST
          #   - name: REACT_APP_CHAT_SERVER_PORT
          #     value: SERVER_CLUSTER_IP_SERVICE_PORT_5002_TCP_PORT