apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    cert-manager.io/issuer: 'letsencrypt-prod'
spec:
  tls:
    - hosts:
      - endlesschat.net
      - www.endlesschat.net
      secretName: endless-chat-net
  rules:
  - host: endlesschat.net
    http:
      paths:
      - path: /?(.*)
        pathType: Prefix
        backend:
          service:
            name: client-cluster-ip-service
            port:
              number: 3000
      - path: /api/?(.*)
        pathType: Prefix
        backend:
          service:
            name: server-cluster-ip-service
            port:
              number: 5003
      - path: /v2/?(.*)
        pathType: Prefix
        backend:
          service:
            name: chat-server-cluster-ip-service
            port:
              number: 8080
  - host: www.endlesschat.net
    http:
      paths:
      - path: /?(.*)
        pathType: Prefix
        backend:
          service:
            name: client-cluster-ip-service
            port:
              number: 3000
      - path: /api/?(.*)
        pathType: Prefix
        backend:
          service:
            name: server-cluster-ip-service
            port:
              number: 5003
      - path: /v2/?(.*)
        pathType: Prefix
        backend:
          service:
            name: chat-server-cluster-ip-service
            port:
              number: 8080
  