name: Java CI with Gradle

on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: ./chatserver

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8


    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: |-
        ./gradlew build --no-daemon
        mkdir -p build/libs/dependency && (cd build/libs/dependency; jar -xf ../chatserver-0.0.1-SNAPSHOT.jar)
        
    - name: Build the Docker image
      run: |-
        docker build \
          --tag "davealonbehr/endless-chat-java-server:latest" \
          --tag "davealonbehr/endless-chat-java-server:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
        
    - name: Publish dockerimage to docker hub
      run: |-
        docker push "davealonbehr/endless-chat-java-server:latest"
        docker push "davealonbehr/endless-chat-java-server:$GITHUB_SHA" 